### ISSUE TITLE
Propose to add a continuous integration tool

### ISSUE THREAD

**Issue by jcooky** [tymsai/marmoym-api#49] opened 2017-08-13 12:54 UTC
This project is needed a CI tool and UnitTest.
It is useful to verify PR.

I want to apply the Travis-CI as a continuous integration tool

**Comment by enginehenryed** [comment] 2017-08-13 13:28
Quite a similar issue with #37. Would you take over it? Let's talk soon.

**Comment by gimochi** [comment] 2017-08-17 13:47
Duplicate of #37

**Closed by gimochi** 2017-08-17 13:47 UTC
Labels: duplicate, Type: Environment
